/**
 *
 * @author
  Chris Cornell
  Temple University
 */

/*
The following code is largely generated by NetBeans in order to
initialize a Java Form (The UI on which the bot operates)
*/

import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class BotForm extends javax.swing.JFrame {

    /**
     * Creates new form BotForm
     */
    public BotForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        label_time = new java.awt.Label();
        button_GO = new javax.swing.JButton();
        checkbox_autoretry = new java.awt.Checkbox();
        label_status = new javax.swing.JLabel();
        choice_timezone = new java.awt.Choice();
        jPanel2 = new javax.swing.JPanel();
        label_billingname = new javax.swing.JLabel();
        text_name = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        label_address = new javax.swing.JLabel();
        text_address = new javax.swing.JTextField();
        text_city = new javax.swing.JTextField();
        label_city = new javax.swing.JLabel();
        text_zipcode = new javax.swing.JTextField();
        label_zip = new javax.swing.JLabel();
        button_loadConfig = new javax.swing.JButton();
        button_saveSettings = new javax.swing.JButton();
        label_billingdets = new javax.swing.JLabel();
        label_itemdets = new javax.swing.JLabel();
        text_phone = new javax.swing.JTextField();
        label_phone = new javax.swing.JLabel();
        label_cc = new javax.swing.JLabel();
        text_ccnum = new javax.swing.JTextField();
        label_ccmonth = new javax.swing.JLabel();
        label_year = new javax.swing.JLabel();
        choice_month = new java.awt.Choice();
        choice_year = new java.awt.Choice();
        label_item = new javax.swing.JLabel();
        text_itemname = new javax.swing.JTextField();
        choice_section = new java.awt.Choice();
        label_section = new javax.swing.JLabel();
        label_size = new java.awt.Label();
        text_size = new javax.swing.JTextField();
        label_color = new javax.swing.JLabel();
        text_color = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        text_cvv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MemeBot");

        runClock();
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        label_time.setAlignment(java.awt.Label.CENTER);
        label_time.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label_time.setFont(new java.awt.Font("Code Bold", 0, 48)); // NOI18N
        label_time.setText("...");

        button_GO.setText("Start Bot");
        button_GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_GOActionPerformed(evt);
            }
        });

        checkbox_autoretry.setLabel("Auto Refresh");
        checkbox_autoretry.setState(true);

        label_status.setText("  ");
        label_status.setToolTipText("");

        String[] zones = {"EST","CST","PST"};

        for(String s : zones)
        choice_timezone.add(s);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 158, Short.MAX_VALUE)
                        .addComponent(choice_timezone, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_status)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button_GO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkbox_autoretry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(label_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_GO)
                    .addComponent(checkbox_autoretry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choice_timezone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_status)
                .addGap(96, 96, 96))
        );

        jTabbedPane1.addTab("Supreme Bot", jPanel1);

        label_billingname.setText("Billing Name");

        text_name.setToolTipText("");

        label_email.setText("Email");

        text_email.setToolTipText("");
        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });

        label_address.setText("Address");

        text_address.setToolTipText("");

        text_city.setToolTipText("");

        label_city.setText("City");

        text_zipcode.setToolTipText("");
        text_zipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_zipcodeActionPerformed(evt);
            }
        });

        label_zip.setText("ZIP");

        button_loadConfig.setText("Load Config...");
        button_loadConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loadConfigActionPerformed(evt);
            }
        });

        button_saveSettings.setText("Save settings");
        button_saveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveSettingsActionPerformed(evt);
            }
        });

        label_billingdets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_billingdets.setText("Billing Details");

        label_itemdets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_itemdets.setText("Item Details");

        text_phone.setToolTipText("");
        text_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_phoneActionPerformed(evt);
            }
        });

        label_phone.setText("Phone");

        label_cc.setText("CC #");

        text_ccnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ccnumActionPerformed(evt);
            }
        });

        label_ccmonth.setText("Month");

        label_year.setText("Year");

        for(int i=1; i<13; i++)
        {
            if(i<10)
            choice_month.add("0" + i);
            else
            choice_month.add("" + i);
        }

        for(int i=2016; i<2024; i++)
        {
            choice_year.add("" + i);
        }

        label_item.setText("Item Name");

        String[] secArray =
        {"jackets","shirts","tops_sweaters","sweatshirts",
            "pants","shorts","hats", "bags", "accessories",
            "skate"
        };

        for(String s : secArray)
        {
            choice_section.add(s);
        }

        label_section.setText("Section");

        label_size.setText("Size");

        label_color.setText("Color");

        jLabel1.setText("CVV");

        text_cvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cvvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_itemdets, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(button_loadConfig)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_saveSettings)
                                    .addGap(12, 12, 12))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(label_city)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(text_city, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label_zip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label_address)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_address, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(label_billingname)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(label_email)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label_phone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_ccmonth)
                            .addComponent(label_year, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_cc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_ccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choice_month, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choice_year, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_item)
                                    .addComponent(label_section))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_itemname, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(text_size, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(choice_section, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label_color)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_color, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(label_billingdets, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_itemdets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_item)
                    .addComponent(text_itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choice_section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_section))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_color)
                        .addComponent(text_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(label_billingdets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_billingname)
                    .addComponent(label_cc)
                    .addComponent(text_ccnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(text_cvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_phone)
                            .addComponent(label_ccmonth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(choice_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_year)
                                .addComponent(label_email))
                            .addComponent(choice_year, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_city))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_zip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_loadConfig)
                    .addComponent(button_saveSettings))
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("Settings", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        //runClock();
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void text_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_phoneActionPerformed

    private void button_loadConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loadConfigActionPerformed
        // TODO add your handling code here:
        cfgName = JOptionPane.showInputDialog("Enter name of config\nEx. bot.config");
        fillBoxes(cfgName);
    }//GEN-LAST:event_button_loadConfigActionPerformed

    private void text_zipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_zipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_zipcodeActionPerformed

    private void text_ccnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ccnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ccnumActionPerformed

    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_emailActionPerformed

    private void text_cvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cvvActionPerformed

    private void button_saveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveSettingsActionPerformed
        // TODO add your handling code here:
        bot = new SupremeBot(text_name.getText(), text_email.getText(), text_phone.getText(),
                            text_address.getText(), text_zipcode.getText(), text_city.getText(),
                            text_ccnum.getText(), text_cvv.getText(), choice_month.getSelectedItem(), choice_year.getSelectedItem(),
                            choice_section.getSelectedItem(), text_itemname.getText(), text_color.getText(), text_size.getText(), "0");
        JOptionPane.showMessageDialog(null,"Settings loaded for item " + text_itemname.getText() + ", size " + text_size.getText() + ", color " + text_color.getText());
    }//GEN-LAST:event_button_saveSettingsActionPerformed

    private void button_GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_GOActionPerformed
        // TODO add your handling code here:
        if( choice_timezone.getSelectedItem().equals("EST") ) { START_TIME = "13:11"; END_TIME = "13:12"; }
        else if (choice_timezone.getSelectedItem().equals("CST") ) { START_TIME = "09:59"; END_TIME = "10:02"; }
        else { START_TIME = "07:59"; END_TIME = "8:02"; }
        if(!activeRetrying) {
            try {
                label_status.setText("Checking for item...");
                if(bot.itemOnPage())
                    bot.start();
                else
                {
                    if(checkbox_autoretry.getState()) // if autoretry is on
                    {
                        label_status.setText("Waiting until " + START_TIME);
                        runTimechecker();
                        button_GO.setText("Stop Bot");
                        activeRetrying=true;
                    }
                    else // if no autoretry
                    {
                        JOptionPane.showMessageDialog(null, "ERROR: Item not found.");
                        label_status.setText("");
                    }
                }
            } catch ( java.lang.NullPointerException e ) { JOptionPane.showMessageDialog(null, "Settings not loaded into bot. Use settings tab."); System.exit(0); }
        }
        else
        {
            tcheck.stop();
            try{ checker.stop(); } catch (java.lang.NullPointerException e ) { }
            activeRetrying=false;
            button_GO.setText("Start Bot");
            label_status.setText("");
            retrycount=0;
        }
    }//GEN-LAST:event_button_GOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotForm().setVisible(true);
            }
        });

    }
    private void fillBoxes(String str)
    {
        //try{
        Config cfg = new Config(str);
        //}
        //catch (IOException e) { }
        text_name.setText(cfg.getValue("bot.billing_name"));
        text_email.setText(cfg.getValue("bot.email"));
        text_phone.setText(cfg.getValue("bot.tel"));
        text_address.setText(cfg.getValue("bot.billing_address"));
        text_zipcode.setText(cfg.getValue("bot.billing_zip"));
        text_city.setText(cfg.getValue("bot.billing_city"));
        text_ccnum.setText(cfg.getValue("bot.cc_number"));
        text_cvv.setText(cfg.getValue("bot.cvv_code"));
        choice_month.select(cfg.getValue("bot.cc_month"));
        choice_year.select(cfg.getValue("bot.cc_year"));

        JOptionPane.showMessageDialog(null, "Config successfully loaded.");
    }

    public void runClock()
    {
        Timer t = new Timer (50, updateClockAction);
        t.start();
    }
    ActionListener updateClockAction = new ActionListener()
    {
        public void actionPerformed(ActionEvent e)
        {
            format = new SimpleDateFormat("HH:mm:ss");
            d = new Date();
            timeString = format.format(d);
            label_time.setText(timeString);
        }
    };

    Timer checker;
    public void runAutochecker()
    {
        checker = new Timer(250, checkForItem);
        checker.start();
    }
    ActionListener checkForItem = new ActionListener()
    {
        public void actionPerformed(ActionEvent e)
        {
            boolean keepchecking=false;
            if(format.format(d).substring(0,5).equals(START_TIME) && !keepchecking) keepchecking=true;
            else if(format.format(d).substring(0,5).equals(END_TIME)) keepchecking=false;
            if(keepchecking)
            {
                retrycount++;
                label_status.setText("Auto-refreshing...retry number " + retrycount);
                if(bot.itemOnPage())
                {
                    bot.start();
                    checker.stop();
                   // bot.start();
                }
            }
        }
    };
    Timer tcheck;
    public void runTimechecker()
    {
        tcheck = new Timer(2500, checkTime);
        tcheck.start();

    }
    ActionListener checkTime = new ActionListener()
    {
        public void actionPerformed(ActionEvent e)
        {
            if(format.format(d).substring(0,5).equals(START_TIME))
            {
                runAutochecker();
                tcheck.stop();
            }
        }
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_GO;
    private javax.swing.JButton button_loadConfig;
    private javax.swing.JButton button_saveSettings;
    private java.awt.Checkbox checkbox_autoretry;
    private java.awt.Choice choice_month;
    private java.awt.Choice choice_section;
    private java.awt.Choice choice_timezone;
    private java.awt.Choice choice_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_billingdets;
    private javax.swing.JLabel label_billingname;
    private javax.swing.JLabel label_cc;
    private javax.swing.JLabel label_ccmonth;
    private javax.swing.JLabel label_city;
    private javax.swing.JLabel label_color;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_item;
    private javax.swing.JLabel label_itemdets;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_section;
    private java.awt.Label label_size;
    private javax.swing.JLabel label_status;
    private java.awt.Label label_time;
    private javax.swing.JLabel label_year;
    private javax.swing.JLabel label_zip;
    private javax.swing.JTextField text_address;
    private javax.swing.JTextField text_ccnum;
    private javax.swing.JTextField text_city;
    private javax.swing.JTextField text_color;
    private javax.swing.JTextField text_cvv;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_itemname;
    private javax.swing.JTextField text_name;
    private javax.swing.JTextField text_phone;
    private javax.swing.JTextField text_size;
    private javax.swing.JTextField text_zipcode;
    // End of variables declaration//GEN-END:variables
    SimpleDateFormat clock = new SimpleDateFormat();
    Date d;
    String timeString;
    DateFormat format;
    String cfgName;
    SupremeBot bot;
    int retrycount=0;
    boolean activeRetrying=false;
    private String START_TIME;
    private String END_TIME;
}
